"""add security question to user

Revision ID: 077163ca7c13
Revises: 2c1142bb8a10
Create Date: 2026-10-06 01:44:52.737012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077163ca7c13'
down_revision = '2c1142bb8a10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.alter_column('validity_percent',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text('(85.0)'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_question', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('security_answer', sa.String(length=512), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.drop_column('security_answer')
        batch_op.drop_column('security_question')

    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.alter_column('validity_percent',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True,
               existing_server_default=sa.text('(85.0)'))

    # ### end Alembic commands ###
