"""increase password_hash length

Revision ID: 2c1142bb8a10
Revises: 66bcd8cf2fbd
Create Date: 2026-10-06 01:04:14.278697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c1142bb8a10'
down_revision = '66bcd8cf2fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.alter_column('validity_percent',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text('(85.0)'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.alter_column('validity_percent',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True,
               existing_server_default=sa.text('(85.0)'))

    # ### end Alembic commands ###
