"""Add CreditCard model

Revision ID: 5129430f1bcc
Revises: 741fd109b2a5
Create Date: 2025-08-11 05:06:53.812374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5129430f1bcc'
down_revision = '741fd109b2a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('card_number', sa.String(length=20), nullable=False),
    sa.Column('card_type', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('bank', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_card')
    # ### end Alembic commands ###
