"""Add wallet address fields to User

Revision ID: 5d1f2715edb6
Revises: 5129430f1bcc
Create Date: 2025-08-11 05:34:34.594156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d1f2715edb6'
down_revision = '5129430f1bcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('btc_wallet_address', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('usdt_wallet_address', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('usdt_wallet_address')
        batch_op.drop_column('btc_wallet_address')

    # ### end Alembic commands ###
