"""Add enhanced card fields for realism

Revision ID: 66bcd8cf2fbd
Revises: 093286446cae
Create Date: 2025-08-18 00:55:42.393549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66bcd8cf2fbd'
down_revision = '093286446cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bin_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('brand', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('level', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('prepaid', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('country_flag', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('note', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.drop_column('note')
        batch_op.drop_column('country_flag')
        batch_op.drop_column('prepaid')
        batch_op.drop_column('level')
        batch_op.drop_column('brand')
        batch_op.drop_column('bin_code')

    # ### end Alembic commands ###
