"""Enhanced CreditCard model with additional fields

Revision ID: 68e77246da37
Revises: e7a76645f4ce
Create Date: 2025-08-18 00:34:09.179018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e77246da37'
down_revision = 'e7a76645f4ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('email_pass', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ssn', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=True))
        batch_op.alter_column('card_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.create_unique_constraint('uq_credit_card_card_number', ['card_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.drop_constraint('uq_credit_card_card_number', type_='unique')
        batch_op.alter_column('card_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.drop_column('is_available')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('dob')
        batch_op.drop_column('ssn')
        batch_op.drop_column('email_pass')
        batch_op.drop_column('email')
        batch_op.drop_column('phone')
        batch_op.drop_column('address')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('city')
        batch_op.drop_column('state')

    # ### end Alembic commands ###
