"""Add card details to CreditCard

Revision ID: e7a76645f4ce
Revises: 5d1f2715edb6
Create Date: 2025-08-13 00:48:26.540620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a76645f4ce'
down_revision = '5d1f2715edb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cvv', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('expiry', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('holder_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.drop_column('balance')
        batch_op.drop_column('price')
        batch_op.drop_column('holder_name')
        batch_op.drop_column('expiry')
        batch_op.drop_column('cvv')

    # ### end Alembic commands ###
